name: location_hub
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management (BLoC)
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Immutable Classes & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Background Service & Location
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  
  # Networking & Storage
  signalr_netcore: ^1.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true